In [2]:
import numpy as np
a = np.array([1,2,3,4,5,6,7])
print(a)

[1 2 3 4 5 6 7]


In [ ]:
#multi dimensional array
a = np.array([(1,2,3),(4,5,6,)])
print(a)

[[1 2 3]
 [4 5 6]]


In [ ]:
#comparing memory occupied by both
import numpy as np
import sys
#memory occupied by list
s = range(1000)
print('memory occupied by list',sys.getsizeof(10)*len(s))
#memory occupied by numpy
d = np.arange(1000)
print('memory occupied by num array',d.size*d.itemsize)

memory occupied by list 28000
memory occupied by num array 8000


In [ ]:
import time
print(time.time())

1673848920.977331


In [ ]:
import time
import numpy as np
#comparing speed of list and numpy array
size = 10000000
#checking list taking time
l1 =range(size)
l2 =range(size)
start = time.time()
result =[(x,y) for x,y in zip(l1,l2)]
print('time taken by list',time.time()-start)
#checking numpy array taken time
a1 =np.arange(size)
a2 =np.arange(size)
start2 =time.time()
result_numpy = a1+a2
print('time taken by numpy',time.time()-start2) 

time taken by list 2.5880987644195557
time taken by numpy 0.05398964881896973


In [ ]:
import numpy as np
a = np.array([(8,9,10),(11,12,13)])
print(a)
b = a.reshape(6,1)
print(b)

[[ 8  9 10]
 [11 12 13]]
[[ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]]


In [ ]:
#It has printed 10 values btw 1 to 3
import numpy as np
a = np.linspace(1,3,10)
print(a)

[1.         1.22222222 1.44444444 1.66666667 1.88888889 2.11111111
 2.33333333 2.55555556 2.77777778 3.        ]


In [3]:
a = np.arange(1,100,2)
print(a)

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95
 97 99]


In [5]:
a = np.arange(0,100,2)
print(a)

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48 50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94
 96 98]
